"""API routers for VPN Simulator v2."""

from vpn_simulator.api.routers import (
    attacks,
    automation,
    benchmark,
    comparison,
    config,
    connections,
    faults,
    iot,
    learning,
    logs,
    metrics,
    obfuscation,
    packets,
    protocols,
    scenarios,
    stats,
    topology,
    traffic,
    tutorials,
)

__all__ = [
    "attacks",
    "automation",
    "benchmark",
    "comparison",
    "config",
    "connections",
    "faults",
    "iot",
    "learning",
    "logs",
    "metrics",
    "obfuscation",
    "packets",
    "protocols",
    "scenarios",
    "stats",
    "topology",
    "traffic",
    "tutorials",
]
